/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AlienGUI;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import realiseringprojekt.AlienInformationPlats;


/**
 *
 * @author ericc
 */
public class InformationGUI extends javax.swing.JFrame {

    /**
     * Creates new form InformationGUI
     */
    private InfDB idb;
    
    public InformationGUI(InfDB idb) {
        initComponents();
        this.idb= idb;
        visaInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAInfo = new javax.swing.JTextArea();
        txtID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("INFROMATION OM OMRÅDESCHEF");

        txtAInfo.setColumns(20);
        txtAInfo.setRows(5);
        jScrollPane1.setViewportView(txtAInfo);

        txtID.setText("1");
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed
    private void visaInformation()
    {
        try{
        String sok= "SELECT Agent.`Namn`, Agent.`Agent_ID`,Agent.`Telefon`,Agent.`Epost`,Agent.`Omrade` from Agent join omradeschef on agent.`Agent_ID`=omradeschef.`Agent_ID` join plats on omradeschef.`Omrade` =plats.`Plats_ID`join alien on plats.`Plats_ID`=alien.`Plats` where alien_ID=1";
       
        ArrayList<HashMap<String,String>> infoMap= idb.fetchRows(sok);
        
        
        for(HashMap<String,String> info: infoMap){
            txtAInfo.append(info.get("Namn")+ "\t");
            txtAInfo.append(info.get("Agent_ID")+ "\t");
            txtAInfo.append(info.get("Telefon")+ "\t");
            txtAInfo.append(info.get("Epost")+ "\t");
            txtAInfo.append(info.get("Omrade")+ "\t");
        }
       
      //  SELECT Agent.`Namn`, Agent.`Agent_ID`,Agent.`Telefon`,Agent.`Epost`,Agent.`Omrade` from Agent
      //  join omradeschef on agent.`Agent_ID`=omradeschef.`Agent_ID`
       // join plats on omradeschef.`Omrade` =plats.`Plats_ID`
      //  join alien on plats.`Plats_ID`=alien.`Plats` where alien_ID=3;
       
           
        
        
        }
        
        catch(InfException e){
            
        JOptionPane.showMessageDialog(null, "Det blev fel");
        System.out.println("Ett internt fel" + e.getMessage());
        }
           
       
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAInfo;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
