/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AlienGUI;

import oru.inf.InfDB;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import realiseringprojekt.AlienInformationPlats;
     
 
/**
 *
 * @author ericc
 */
public class ListAliensGUI extends javax.swing.JFrame {


    private InfDB idb;
    
    public ListAliensGUI(InfDB idb) {
        initComponents();
        this.idb= idb;
        listAllAliens();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtALista = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setText("Aliens i mitt område");

        txtALista.setColumns(20);
        txtALista.setRows(5);
        jScrollPane1.setViewportView(txtALista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listAllAliens(){
        
        try{
            ArrayList<String> listaAlien= idb.fetchColumn("SELECT Namn FROM alien where plats = 2");

            for(String namn:listaAlien){
                txtALista.append(namn + "\n");
            }
     
            }   
        catch(InfException e){
            
        JOptionPane.showMessageDialog(null, "Det blev fel");
        System.out.println("Ett internt fel" + e.getMessage());
        }
     
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextArea txtALista;
    // End of variables declaration//GEN-END:variables
}
