/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realiseringprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author leyla
 */
public class AdminSida extends javax.swing.JFrame {

    private InfDB idb;

    /**
     * Creates new form AdminSida
     */
    public AdminSida(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHelaBakgrund = new javax.swing.JPanel();
        pnlSideBar = new javax.swing.JPanel();
        lblMIBSektorSkandinavien = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        btnStatistik = new javax.swing.JButton();
        btnAndraInformation = new javax.swing.JButton();
        btnTaBortUtrustning = new javax.swing.JButton();
        btnGeAdmin = new javax.swing.JButton();
        btnRadera = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();
        jPlats = new javax.swing.JButton();
        jRas = new javax.swing.JButton();
        jNyUtrustning = new javax.swing.JButton();
        jDatum = new javax.swing.JButton();
        txtSokAgentRuta = new javax.swing.JTextField();
        pnlVitRutaMainAction = new javax.swing.JPanel();
        pnl1Valkommen = new javax.swing.JPanel();
        pnlBildMIB = new javax.swing.JLabel();
        pnlRegistrering = new javax.swing.JPanel();
        txtRegistreringRubrik = new javax.swing.JLabel();
        lblValjRoll = new javax.swing.JLabel();
        btnValjAlien = new javax.swing.JButton();
        btnValjAgent = new javax.swing.JButton();
        pnlRegistreraAgent = new javax.swing.JPanel();
        lblRegistreraAgent = new javax.swing.JLabel();
        txtSkrivAgentID = new javax.swing.JTextField();
        lblAgentID = new javax.swing.JLabel();
        lblAgentNamn = new javax.swing.JLabel();
        txtSkrivAgentNamn = new javax.swing.JTextField();
        lblAgentTelefon = new javax.swing.JLabel();
        txtSkrivAgentTelefon = new javax.swing.JTextField();
        lblAgentDatum = new javax.swing.JLabel();
        txtSkrivAgentDatum = new javax.swing.JTextField();
        lblAgentAdmin = new javax.swing.JLabel();
        txtSkrivAgentAdmin = new javax.swing.JTextField();
        lblAgentEpost = new javax.swing.JLabel();
        txtSkrivAgentEpost = new javax.swing.JTextField();
        lblAgentLosenord = new javax.swing.JLabel();
        txtAgentLosenord = new javax.swing.JTextField();
        lblAgentOmrade = new javax.swing.JLabel();
        txtSkrivAgentOmrade = new javax.swing.JTextField();
        btnRegistreraAgent = new javax.swing.JButton();
        btnGaTillbakaRegistrering = new javax.swing.JButton();
        pnlRegistreraAlien = new javax.swing.JPanel();
        lblRegistreraAlien = new javax.swing.JLabel();
        lblAlienID = new javax.swing.JLabel();
        txtSkrivaAlienID = new javax.swing.JTextField();
        lblAlienNamn = new javax.swing.JLabel();
        txtSkrivaAlienNamn = new javax.swing.JTextField();
        txtSkrivaAlienLosenord = new javax.swing.JTextField();
        lblAlienLosenord = new javax.swing.JLabel();
        lblAlienTelefon = new javax.swing.JLabel();
        txtAlienTelefon = new javax.swing.JTextField();
        lblAlienPlats = new javax.swing.JLabel();
        txtAlienPlats = new javax.swing.JTextField();
        lblAlienAgent = new javax.swing.JLabel();
        lblAlienDatum = new javax.swing.JLabel();
        lblAlienEpost = new javax.swing.JLabel();
        txtAlienEpost = new javax.swing.JTextField();
        txtAlienDatum = new javax.swing.JTextField();
        txtAlienAgent = new javax.swing.JTextField();
        btnAlienRegistrera = new javax.swing.JButton();
        btnAlienTillbaka = new javax.swing.JButton();
        lblAlienFelMeddelande = new javax.swing.JLabel();
        pnlTaBortUtrustning = new javax.swing.JPanel();
        lblUtrustning = new javax.swing.JLabel();
        lblSkrivInUtrustning = new javax.swing.JLabel();
        txtSkrivUtrustning = new javax.swing.JTextField();
        btnUtrustningRadering = new javax.swing.JButton();
        lblUtrustningRaderad = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHelaBakgrund.setBackground(new java.awt.Color(153, 153, 153));

        pnlSideBar.setBackground(new java.awt.Color(51, 51, 51));

        lblMIBSektorSkandinavien.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblMIBSektorSkandinavien.setForeground(new java.awt.Color(255, 255, 255));
        lblMIBSektorSkandinavien.setText("MIB Sektor Skandinavien");

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdmin.setText("Administratör");

        btnRegistrera.setBackground(new java.awt.Color(0, 102, 0));
        btnRegistrera.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrera.setText("Registrera alien/agent");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        btnStatistik.setBackground(new java.awt.Color(0, 102, 0));
        btnStatistik.setForeground(new java.awt.Color(255, 255, 255));
        btnStatistik.setText("Systemstatistik");

        btnAndraInformation.setBackground(new java.awt.Color(0, 102, 0));
        btnAndraInformation.setForeground(new java.awt.Color(255, 255, 255));
        btnAndraInformation.setText("Ändra information");
        btnAndraInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInformationActionPerformed(evt);
            }
        });

        btnTaBortUtrustning.setBackground(new java.awt.Color(0, 102, 0));
        btnTaBortUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        btnTaBortUtrustning.setText("Ta bort utrustning");
        btnTaBortUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortUtrustningActionPerformed(evt);
            }
        });

        btnGeAdmin.setBackground(new java.awt.Color(0, 102, 0));
        btnGeAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnGeAdmin.setText("Ge administratörsstatus");

        btnRadera.setBackground(new java.awt.Color(153, 0, 0));
        btnRadera.setForeground(new java.awt.Color(255, 255, 255));
        btnRadera.setText("Ta bort alien/agent");
        btnRadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaderaActionPerformed(evt);
            }
        });

        btnLoggaUt.setBackground(new java.awt.Color(51, 51, 51));
        btnLoggaUt.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        jPlats.setText("plats");
        jPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlatsActionPerformed(evt);
            }
        });

        jRas.setText("Ras");
        jRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRasActionPerformed(evt);
            }
        });

        jNyUtrustning.setText("Registrera ny utrustning");
        jNyUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNyUtrustningActionPerformed(evt);
            }
        });

        jDatum.setText("Datum");
        jDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlSideBarLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(lblAdmin))
                        .addGroup(pnlSideBarLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMIBSektorSkandinavien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAndraInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRadera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoggaUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlSideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jRas, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                        .addGroup(pnlSideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jNyUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlSideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlSideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblMIBSektorSkandinavien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAndraInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaBortUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPlats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNyUtrustning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        txtSokAgentRuta.setBackground(new java.awt.Color(102, 102, 102));
        txtSokAgentRuta.setForeground(new java.awt.Color(255, 255, 255));
        txtSokAgentRuta.setText("Sök agent...");
        txtSokAgentRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSokAgentRutaActionPerformed(evt);
            }
        });

        pnlVitRutaMainAction.setBackground(new java.awt.Color(255, 255, 255));
        pnlVitRutaMainAction.setLayout(new java.awt.CardLayout());

        pnl1Valkommen.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnl1ValkommenLayout = new javax.swing.GroupLayout(pnl1Valkommen);
        pnl1Valkommen.setLayout(pnl1ValkommenLayout);
        pnl1ValkommenLayout.setHorizontalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1ValkommenLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(pnlBildMIB, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        pnl1ValkommenLayout.setVerticalGroup(
            pnl1ValkommenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1ValkommenLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(pnlBildMIB)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pnlVitRutaMainAction.add(pnl1Valkommen, "card4");

        pnlRegistrering.setBackground(new java.awt.Color(51, 51, 51));

        txtRegistreringRubrik.setBackground(new java.awt.Color(0, 0, 0));
        txtRegistreringRubrik.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtRegistreringRubrik.setForeground(new java.awt.Color(255, 255, 255));
        txtRegistreringRubrik.setText("Registrering");

        lblValjRoll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblValjRoll.setForeground(new java.awt.Color(255, 255, 255));
        lblValjRoll.setText("Välj vad vill du registrera in till systemet");

        btnValjAlien.setBackground(new java.awt.Color(51, 0, 153));
        btnValjAlien.setForeground(new java.awt.Color(255, 255, 255));
        btnValjAlien.setText("Alien");
        btnValjAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjAlienActionPerformed(evt);
            }
        });

        btnValjAgent.setBackground(new java.awt.Color(0, 102, 0));
        btnValjAgent.setForeground(new java.awt.Color(255, 255, 255));
        btnValjAgent.setText("Agent");
        btnValjAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValjAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistreringLayout = new javax.swing.GroupLayout(pnlRegistrering);
        pnlRegistrering.setLayout(pnlRegistreringLayout);
        pnlRegistreringLayout.setHorizontalGroup(
            pnlRegistreringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreringLayout.createSequentialGroup()
                .addGroup(pnlRegistreringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistreringLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(txtRegistreringRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistreringLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnValjAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegistreringLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblValjRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlRegistreringLayout.setVerticalGroup(
            pnlRegistreringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreringLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtRegistreringRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblValjRoll)
                .addGap(25, 25, 25)
                .addGroup(pnlRegistreringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValjAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValjAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pnlVitRutaMainAction.add(pnlRegistrering, "card2");

        pnlRegistreraAgent.setBackground(new java.awt.Color(51, 51, 51));

        lblRegistreraAgent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistreraAgent.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistreraAgent.setText("Registrera agent");

        lblAgentID.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentID.setText("Agent_ID");

        lblAgentNamn.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentNamn.setText("Namn");

        lblAgentTelefon.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentTelefon.setText("Telefon");

        lblAgentDatum.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentDatum.setText("Anställningsdatum");

        txtSkrivAgentDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkrivAgentDatumActionPerformed(evt);
            }
        });

        lblAgentAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentAdmin.setText("Administratör");

        lblAgentEpost.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentEpost.setText("E-post");

        lblAgentLosenord.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentLosenord.setText("Lösenord");

        lblAgentOmrade.setForeground(new java.awt.Color(255, 255, 255));
        lblAgentOmrade.setText("Område");

        txtSkrivAgentOmrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkrivAgentOmradeActionPerformed(evt);
            }
        });

        btnRegistreraAgent.setBackground(new java.awt.Color(0, 153, 0));
        btnRegistreraAgent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistreraAgent.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistreraAgent.setText("Registrera");
        btnRegistreraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraAgentActionPerformed(evt);
            }
        });

        btnGaTillbakaRegistrering.setBackground(new java.awt.Color(0, 51, 102));
        btnGaTillbakaRegistrering.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGaTillbakaRegistrering.setForeground(new java.awt.Color(255, 255, 255));
        btnGaTillbakaRegistrering.setText("Gå tillbaka");
        btnGaTillbakaRegistrering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaTillbakaRegistreringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistreraAgentLayout = new javax.swing.GroupLayout(pnlRegistreraAgent);
        pnlRegistreraAgent.setLayout(pnlRegistreraAgentLayout);
        pnlRegistreraAgentLayout.setHorizontalGroup(
            pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                        .addComponent(btnRegistreraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnGaTillbakaRegistrering, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                        .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegistreraAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgentDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(lblAgentTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSkrivAgentID)
                                    .addComponent(txtSkrivAgentNamn)
                                    .addComponent(txtSkrivAgentTelefon)
                                    .addComponent(txtSkrivAgentDatum))
                                .addGap(60, 60, 60)
                                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgentAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentEpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAgentOmrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAgentLosenord)
                                    .addComponent(txtSkrivAgentOmrade)
                                    .addComponent(txtSkrivAgentEpost)
                                    .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                                        .addComponent(txtSkrivAgentAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 42, Short.MAX_VALUE)))))
                        .addGap(314, 314, 314))))
        );
        pnlRegistreraAgentLayout.setVerticalGroup(
            pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreraAgentLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRegistreraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgentAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSkrivAgentID, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtSkrivAgentAdmin))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentEpost)
                    .addComponent(lblAgentNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSkrivAgentNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtSkrivAgentEpost))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentTelefon)
                    .addComponent(lblAgentLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSkrivAgentTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtAgentLosenord))
                .addGap(18, 18, 18)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAgentDatum)
                    .addComponent(lblAgentOmrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSkrivAgentDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkrivAgentOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlRegistreraAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistreraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGaTillbakaRegistrering, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pnlVitRutaMainAction.add(pnlRegistreraAgent, "card5");

        pnlRegistreraAlien.setBackground(new java.awt.Color(51, 51, 51));

        lblRegistreraAlien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistreraAlien.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistreraAlien.setText("Registrera alien");

        lblAlienID.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienID.setText("Alien-ID");

        txtSkrivaAlienID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkrivaAlienIDActionPerformed(evt);
            }
        });

        lblAlienNamn.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienNamn.setText("Namn");

        lblAlienLosenord.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienLosenord.setText("Lösenord");

        lblAlienTelefon.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienTelefon.setText("Telefon");

        lblAlienPlats.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienPlats.setText("Plats");

        lblAlienAgent.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienAgent.setText("Ansvarig agent");

        lblAlienDatum.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienDatum.setText("Registreringsdatum");

        lblAlienEpost.setForeground(new java.awt.Color(255, 255, 255));
        lblAlienEpost.setText("E-post");

        txtAlienDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlienDatumActionPerformed(evt);
            }
        });

        btnAlienRegistrera.setBackground(new java.awt.Color(0, 102, 0));
        btnAlienRegistrera.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlienRegistrera.setForeground(new java.awt.Color(255, 255, 255));
        btnAlienRegistrera.setText("Registrera");
        btnAlienRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienRegistreraActionPerformed(evt);
            }
        });

        btnAlienTillbaka.setBackground(new java.awt.Color(0, 51, 102));
        btnAlienTillbaka.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAlienTillbaka.setForeground(new java.awt.Color(255, 255, 255));
        btnAlienTillbaka.setText("Gå tillbaka");
        btnAlienTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlienTillbakaActionPerformed(evt);
            }
        });

        lblAlienFelMeddelande.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAlienFelMeddelande.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlRegistreraAlienLayout = new javax.swing.GroupLayout(pnlRegistreraAlien);
        pnlRegistreraAlien.setLayout(pnlRegistreraAlienLayout);
        pnlRegistreraAlienLayout.setHorizontalGroup(
            pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                                .addComponent(btnAlienRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnAlienTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRegistreraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlienNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAlienTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSkrivaAlienID, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txtSkrivaAlienNamn)
                                    .addComponent(txtSkrivaAlienLosenord)
                                    .addComponent(txtAlienTelefon))
                                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAlienAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtAlienEpost, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAlienEpost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtAlienDatum, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAlienDatum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                                    .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAlienPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAlienPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAlienAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblAlienFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlRegistreraAlienLayout.setVerticalGroup(
            pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistreraAlienLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRegistreraAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlienPlats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSkrivaAlienID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlienPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAlienAgent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAlienNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlienAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkrivaAlienNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienLosenord)
                    .addComponent(lblAlienDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSkrivaAlienLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlienDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienTelefon)
                    .addComponent(lblAlienEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlienTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlienEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlRegistreraAlienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlienRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlienTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAlienFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlVitRutaMainAction.add(pnlRegistreraAlien, "card6");

        pnlTaBortUtrustning.setBackground(new java.awt.Color(51, 51, 51));

        lblUtrustning.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        lblUtrustning.setText("Ta bort utrustning ur systemet");

        lblSkrivInUtrustning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSkrivInUtrustning.setForeground(new java.awt.Color(255, 255, 255));
        lblSkrivInUtrustning.setText("Skriv in namnet på utrustningen som ska tas bort");

        btnUtrustningRadering.setBackground(new java.awt.Color(153, 0, 0));
        btnUtrustningRadering.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUtrustningRadering.setForeground(new java.awt.Color(255, 255, 255));
        btnUtrustningRadering.setText("Ta bort");
        btnUtrustningRadering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtrustningRaderingActionPerformed(evt);
            }
        });

        lblUtrustningRaderad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUtrustningRaderad.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout pnlTaBortUtrustningLayout = new javax.swing.GroupLayout(pnlTaBortUtrustning);
        pnlTaBortUtrustning.setLayout(pnlTaBortUtrustningLayout);
        pnlTaBortUtrustningLayout.setHorizontalGroup(
            pnlTaBortUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaBortUtrustningLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlTaBortUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUtrustningRaderad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUtrustningRadering, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkrivUtrustning)
                    .addComponent(lblSkrivInUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        pnlTaBortUtrustningLayout.setVerticalGroup(
            pnlTaBortUtrustningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaBortUtrustningLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblSkrivInUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSkrivUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUtrustningRadering, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUtrustningRaderad, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pnlVitRutaMainAction.add(pnlTaBortUtrustning, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 532, Short.MAX_VALUE)
        );

        pnlVitRutaMainAction.add(jPanel1, "card7");

        javax.swing.GroupLayout pnlHelaBakgrundLayout = new javax.swing.GroupLayout(pnlHelaBakgrund);
        pnlHelaBakgrund.setLayout(pnlHelaBakgrundLayout);
        pnlHelaBakgrundLayout.setHorizontalGroup(
            pnlHelaBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelaBakgrundLayout.createSequentialGroup()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlHelaBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlVitRutaMainAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSokAgentRuta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHelaBakgrundLayout.setVerticalGroup(
            pnlHelaBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlHelaBakgrundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtSokAgentRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlVitRutaMainAction, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(pnlHelaBakgrundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelaBakgrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelaBakgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSokAgentRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSokAgentRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSokAgentRutaActionPerformed

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        // Knappp i sidebar för att ta användaren till registrering av agenter/aliens
        panelerGomda();
        pnlRegistrering.show();         
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        // TODO add your handling code here:
        Inloggning inloggning  = new Inloggning(idb);
        inloggning.show();
        dispose();
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnAndraInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndraInformationActionPerformed

    private void txtSkrivAgentDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkrivAgentDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkrivAgentDatumActionPerformed

    private void txtSkrivAgentOmradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkrivAgentOmradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkrivAgentOmradeActionPerformed

    private void btnValjAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjAgentActionPerformed
        // Knappen tar en till panel för att registrera agent
        panelerGomda();
        pnlRegistreraAgent.show();
    }//GEN-LAST:event_btnValjAgentActionPerformed

    private void btnGaTillbakaRegistreringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaTillbakaRegistreringActionPerformed
        // Knappen tar användaren tillbaka till registreringssidan från registrera agent
        panelerGomda();
        pnlRegistrering.show();
    }//GEN-LAST:event_btnGaTillbakaRegistreringActionPerformed

    private void txtSkrivaAlienIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkrivaAlienIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkrivaAlienIDActionPerformed

    private void txtAlienDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlienDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlienDatumActionPerformed

    private void btnAlienRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienRegistreraActionPerformed
        // Knappen i aliensidan för att registrera en alien in till databasen
        String fraga = alienRegistreringFraga();
        
        //Lokala metoder i denna klass + anrop till alienVillkorFyllda() använder sig utav valideringsklassen
        if(alienVillkorFyllda()) {
            try {
                idb.insert(fraga);
                lblAlienFelMeddelande.setText("Alien har nu registrerats.");
            }
            
            catch(InfException fel) {
                lblAlienFelMeddelande.setText("Ett fel uppstod vid registrering!");
            }
        }
    }//GEN-LAST:event_btnAlienRegistreraActionPerformed

    
    private boolean alienVillkorFyllda() {
        //Tittar på ifall valideringsklassens villkor för alien-registrering email, datum och ifyllda rutor är uppfyllda
        boolean villkorFylld = true;
        
        //Villkor som använder metoder utifrån Validering-klassen
        if(!Validering.giltigEpost(txtAlienEpost)) {
            lblAlienFelMeddelande.setText("Ej giltig e-post! E-post måste innehålla '@' mellan namn och domän");
            villkorFylld = false;
        }

        if(Validering.giltigAgentEpost(txtAlienEpost)) {
            lblAlienFelMeddelande.setText("Alien e-post får inte ha '@mib.net' som domän");
            villkorFylld = false;
        }

        if(!Validering.korrektDatum(txtAlienDatum)) {
            lblAlienFelMeddelande.setText("Ej giltigt datum! Var vänligen att ange i detta format: YYYY-MM-DD");
            villkorFylld = false;
        }

        if(!alienRegistreringRutaVarde()) {
            lblAlienFelMeddelande.setText("Var vänlig och fyll i alla rutor korrekt.");
            villkorFylld = false;
        }
        
        if (!(finnsAlienRegistreringAgent() && finnsAlienRegistreringPlats() &&
          !finnsAlienIDRedan() && !finnsAlienEpostRedan() && !finnsAlienTelefonRedan())) {
            villkorFylld = false;
        }
        /*if(finnsAlienRegistreringAgent() && finnsAlienRegistreringPlats() &&
           !finnsAlienIDRedan() && !finnsAlienEpostRedan() && !finnsAlienTelefonRedan()) {
            villkorFylld = true;
        }*/
        return villkorFylld;
    }
    
    
    private boolean finnsAlienIDRedan(){
        //Denna metod tittar på ifall aliens ID som angavs i Alien-registrering existerar
        ArrayList<String> alienID = new ArrayList<String>();
        boolean finns = false;
        String angivenID = txtSkrivaAlienID.getText();
        
        try {
            alienID = idb.fetchColumn("SELECT ALIEN_ID FROM alien");
            
            for(String enAlienID : alienID) {
                if(enAlienID.equals(angivenID)) {
                finns = true;
                lblAlienFelMeddelande.setText("Alien-ID:n som angavs existerar redan!");
                }
            }
        }  
        catch(InfException fel) {
            lblAlienFelMeddelande.setText("Ett fel uppstod med ID:t!");
        }      
        return finns;
    }
    
    
    private boolean finnsAlienEpostRedan() {
        //Denna metod tittar på ifall aliens Epost som angavs i Alien-registrering existerar redan
        ArrayList<String> alienEpost = new ArrayList<String>();
        boolean finns = false;
        String angivenEpost = txtAlienEpost.getText();
        
        try {
            alienEpost = idb.fetchColumn("SELECT Epost FROM alien");
            
            for(String enEpost : alienEpost) {
                if(enEpost.equalsIgnoreCase(angivenEpost)) {
                finns = true;
                lblAlienFelMeddelande.setText("E-posten som angavs existerar redan!");
                }
            }
        }       
        catch(InfException fel) {
            lblAlienFelMeddelande.setText("Ett fel uppstod med e-posten!");
        }     
        return finns;
    }
    
    
    private boolean finnsAlienTelefonRedan() {
        //Tittar om telefonnumret som skrevs in i alien-registrering redan existerar
        ArrayList<String> alienTelefon = new ArrayList<String>();
        boolean finns = false;
        String angivenTelefon = txtAlienTelefon.getText();
        
        try {
        alienTelefon = idb.fetchColumn("SELECT Telefon FROM alien");
        
        for(String enTelefon:alienTelefon) {
            if(enTelefon.equals(angivenTelefon)) {
                finns = true;
                lblAlienFelMeddelande.setText("Telefonnumret som angavs existerar redan!");
                }
            }
        }
        catch(InfException fel) {
            lblAlienFelMeddelande.setText("Ett fel uppstod med telefonnumret!");
        }
        
        return finns;
    }
    
    
    private boolean finnsAlienRegistreringAgent() {
        //Denna metod tittar på ifall agentens ID som angavs i Alien-registrering existerar
        ArrayList<String> agentID = new ArrayList<String>();
        boolean hittad = false;
        String angivenAgentID = txtAlienAgent.getText();
        
        try {
            agentID = idb.fetchColumn("SELECT AGENT_ID FROM agent");
            
            for(String enAgentID : agentID) {
                if(enAgentID.equals(angivenAgentID)) {
                hittad = true;
                }
            }
        }       
        catch(InfException fel) {
            lblAlienFelMeddelande.setText("Ett fel uppstod med agenten som angavs!");
        }

        if(!hittad) {
            lblAlienFelMeddelande.setText("Agenten som angavs existerar ej!");
        }
        
        return hittad;
    }
    
    
    private boolean finnsAlienRegistreringPlats() {
        //Denna metod tittar på ifall aliens plats som angavs i Alien-registrering existerar
        ArrayList<String> platser = new ArrayList<String>();
        boolean hittad = false;
        String alienPlats = txtAlienPlats.getText();
        
        try {
            platser = idb.fetchColumn("SELECT PLATS_ID FROM plats");
            
            for(String enPlats : platser) {
                if(enPlats.equals(alienPlats)) {
                hittad = true;
                }
            }
        }       
        catch(InfException fel) {
            lblAlienFelMeddelande.setText("Ett fel uppstod med platsen som angavs!");
        }
        
        if(!hittad) {
            lblAlienFelMeddelande.setText("Platsen som angavs existerar ej!");
        }
        
        return hittad;
    }
    
    
    private String alienRegistreringFraga() {
        //Bildar frågan för att kunna genomföra en insert till alien-tabellen för registrering av alien
        return "INSERT INTO alien VALUES('" + txtSkrivaAlienID.getText() + "','"
                + txtAlienDatum.getText() + "','"
                + txtAlienEpost.getText() + "','"
                + txtSkrivaAlienLosenord.getText() + "','"
                + txtSkrivaAlienNamn.getText() + "','"
                + txtAlienTelefon.getText() + "','"
                + txtAlienPlats.getText() + "','"
                + txtAlienAgent.getText() + "')";
    }
    
    private boolean alienRegistreringRutaVarde() {
        //Tittar på ifall rutorna i alien-registrerings panelen har värden (alltså är ej tomma)
        return Validering.rutaHarVarde(txtSkrivaAlienID) && Validering.rutaHarVarde(txtSkrivaAlienNamn) && 
                Validering.rutaHarVarde(txtSkrivaAlienLosenord) && Validering.rutaHarVarde(txtAlienTelefon) &&
                Validering.rutaHarVarde(txtAlienPlats) && Validering.rutaHarVarde(txtAlienAgent) && 
                Validering.rutaHarVarde(txtAlienDatum) && Validering.rutaHarVarde(txtAlienEpost);
    }
    
    
    private void btnAlienTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlienTillbakaActionPerformed
        // Gå-tillbaka knappen i registrera alien-sidan
        panelerGomda();
        pnlRegistrering.show();
    }//GEN-LAST:event_btnAlienTillbakaActionPerformed

    
    private void btnValjAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValjAlienActionPerformed
        // Knappen som tar en til registrera alien-sidan
        panelerGomda();
        pnlRegistreraAlien.show();      
    }//GEN-LAST:event_btnValjAlienActionPerformed

    
    private void btnUtrustningRaderingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtrustningRaderingActionPerformed
        // Knapp för att ta bort utrustning
        
        String utrustningRuta = txtSkrivUtrustning.getText();
        String fraga = "SELECT Utrustnings_ID, Benamning FROM utrustning";
        boolean hittad = false;
        
        try {            
            ArrayList<HashMap<String, String>> utrustningar = idb.fetchRows(fraga);
            
            for(HashMap<String, String> enUtrustning : utrustningar) {
                String utrustningNamn = enUtrustning.get("Benamning");
                String id = enUtrustning.get("Utrustnings_ID");
                                        
                if(!utrustningRuta.isEmpty() && utrustningRuta.equalsIgnoreCase(utrustningNamn)) {
                    //Kallar på radera-metoden i samma klass
                    radera(id);            
                    lblUtrustningRaderad.setText(utrustningNamn + " har raderats");
                    hittad = true;
                }                
            }
            if(!hittad) {
            lblUtrustningRaderad.setText("Utrustningen existerar ej."); 
            }
        } 
        catch (InfException fel) {
            lblUtrustningRaderad.setText("Ett fel uppstod!");
        }    
    }//GEN-LAST:event_btnUtrustningRaderingActionPerformed

    
    private void radera(String id) {
        //Alla kallelser till databasen för radering av utrustning sker genom delete-metoden        
        try {
        idb.delete("DELETE FROM kommunikation WHERE Utrustnings_ID=" + id);
        idb.delete("DELETE FROM teknik WHERE Utrustnings_ID=" + id);
        idb.delete("DELETE FROM vapen WHERE Utrustnings_ID=" + id);
        idb.delete("DELETE FROM innehar_utrustning WHERE Utrustnings_ID=" + id);           
        idb.delete("DELETE FROM utrustning WHERE Utrustnings_ID=" + id); 
        }     
        catch (InfException fel){
          lblUtrustningRaderad.setText("Ett fel uppstod vid borttagning av utrustning!");
        }
    }
        
    private void btnTaBortUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortUtrustningActionPerformed
        // Knapp i sidebar som tar en till funktion för att ta bort utrustning ur systemet
        panelerGomda();
        pnlTaBortUtrustning.show();
    }//GEN-LAST:event_btnTaBortUtrustningActionPerformed

    private void btnRegistreraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraAgentActionPerformed
        // Knappen registrerar en agent ifall villkoren uppfylls
        String fraga = agentRegistreringsFraga();
        
        if(Validering.giltigAgentEpost(txtSkrivAgentEpost)) {
            
        }
    }//GEN-LAST:event_btnRegistreraAgentActionPerformed

    private void jPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlatsActionPerformed
        AlienInformationPlats plats = new AlienInformationPlats(idb);
        plats.setVisible(true);
    }//GEN-LAST:event_jPlatsActionPerformed

    private void jRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRasActionPerformed
       AlienInformationRas ras = new AlienInformationRas(idb);
        ras.setVisible(true);
    }//GEN-LAST:event_jRasActionPerformed

    private void jNyUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNyUtrustningActionPerformed
        RegistreraNyUtrustning utrustning = new RegistreraNyUtrustning(idb);
        utrustning.setVisible(true);
                
    }//GEN-LAST:event_jNyUtrustningActionPerformed

    private void btnRaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRaderaActionPerformed

    private void jDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatumActionPerformed
       AliensInformationDatum datum = new AliensInformationDatum(idb);
        datum.setVisible(true);
    }//GEN-LAST:event_jDatumActionPerformed

    private String agentRegistreringFraga() {
        //Bildar frågan för att kunna genomföra en insert till agent-tabellen för registrering av agent
        return "INSERT INTO agent VALUES('" + txtSkrivAgentID.getText() + "','"
                + txtSkrivAgentNamn.getText() + "','"
                + txtSkrivAgentTelefon.getText() + "','"
                + txtSkrivAgentDatum.getText() + "','"
                + txtSkrivAgentAdmin.getText() + "','"
                + txtSkrivAgentEpost.getText() + "','"
                + txtAgentLosenord.getText() + "','"
                + txtSkrivAgentOmrade.getText() + "')";
    }
    
    private boolean agentRegistreringRutaVarde() {
        //Tittar på ifall rutorna i agent-registrerings panelen har värden (alltså är ej tomma)
        return Validering.rutaHarVarde(txtSkrivAgentID) && Validering.rutaHarVarde(txtSkrivAgentNamn) && 
                Validering.rutaHarVarde(txtAgentLosenord) && Validering.rutaHarVarde(txtSkrivAgentTelefon) &&
                Validering.rutaHarVarde(txtSkrivAgentOmrade) && Validering.rutaHarVarde(txtSkrivAgentAdmin) && 
                Validering.rutaHarVarde(txtSkrivAgentDatum) && Validering.rutaHarVarde(txtSkrivAgentEpost);
    }
    

    private void panelerGomda() {
        //Alla gömda paneler samlade i en metod för att förenkla koden
        pnl1Valkommen.hide();
        pnlRegistreraAgent.hide();
        pnlRegistreraAlien.hide();
        pnlRegistrering.hide();
        pnlTaBortUtrustning.hide();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlienRegistrera;
    private javax.swing.JButton btnAlienTillbaka;
    private javax.swing.JButton btnAndraInformation;
    private javax.swing.JButton btnGaTillbakaRegistrering;
    private javax.swing.JButton btnGeAdmin;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnRadera;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnRegistreraAgent;
    private javax.swing.JButton btnStatistik;
    private javax.swing.JButton btnTaBortUtrustning;
    private javax.swing.JButton btnUtrustningRadering;
    private javax.swing.JButton btnValjAgent;
    private javax.swing.JButton btnValjAlien;
    private javax.swing.JButton jDatum;
    private javax.swing.JButton jNyUtrustning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jPlats;
    private javax.swing.JButton jRas;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAgentAdmin;
    private javax.swing.JLabel lblAgentDatum;
    private javax.swing.JLabel lblAgentEpost;
    private javax.swing.JLabel lblAgentID;
    private javax.swing.JLabel lblAgentLosenord;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblAgentOmrade;
    private javax.swing.JLabel lblAgentTelefon;
    private javax.swing.JLabel lblAlienAgent;
    private javax.swing.JLabel lblAlienDatum;
    private javax.swing.JLabel lblAlienEpost;
    private javax.swing.JLabel lblAlienFelMeddelande;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblAlienLosenord;
    private javax.swing.JLabel lblAlienNamn;
    private javax.swing.JLabel lblAlienPlats;
    private javax.swing.JLabel lblAlienTelefon;
    private javax.swing.JLabel lblMIBSektorSkandinavien;
    private javax.swing.JLabel lblRegistreraAgent;
    private javax.swing.JLabel lblRegistreraAlien;
    private javax.swing.JLabel lblSkrivInUtrustning;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JLabel lblUtrustningRaderad;
    private javax.swing.JLabel lblValjRoll;
    private javax.swing.JPanel pnl1Valkommen;
    private javax.swing.JLabel pnlBildMIB;
    private javax.swing.JPanel pnlHelaBakgrund;
    private javax.swing.JPanel pnlRegistreraAgent;
    private javax.swing.JPanel pnlRegistreraAlien;
    private javax.swing.JPanel pnlRegistrering;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JPanel pnlTaBortUtrustning;
    private javax.swing.JPanel pnlVitRutaMainAction;
    private javax.swing.JTextField txtAgentLosenord;
    private javax.swing.JTextField txtAlienAgent;
    private javax.swing.JTextField txtAlienDatum;
    private javax.swing.JTextField txtAlienEpost;
    private javax.swing.JTextField txtAlienPlats;
    private javax.swing.JTextField txtAlienTelefon;
    private javax.swing.JLabel txtRegistreringRubrik;
    private javax.swing.JTextField txtSkrivAgentAdmin;
    private javax.swing.JTextField txtSkrivAgentDatum;
    private javax.swing.JTextField txtSkrivAgentEpost;
    private javax.swing.JTextField txtSkrivAgentID;
    private javax.swing.JTextField txtSkrivAgentNamn;
    private javax.swing.JTextField txtSkrivAgentOmrade;
    private javax.swing.JTextField txtSkrivAgentTelefon;
    private javax.swing.JTextField txtSkrivUtrustning;
    private javax.swing.JTextField txtSkrivaAlienID;
    private javax.swing.JTextField txtSkrivaAlienLosenord;
    private javax.swing.JTextField txtSkrivaAlienNamn;
    private javax.swing.JTextField txtSokAgentRuta;
    // End of variables declaration//GEN-END:variables

    private String agentRegistreringsFraga() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
