/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package realiseringprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author charolinnoaaman
 */
public class AlienInformationPlats extends javax.swing.JFrame {
private InfDB idb;
private DefaultListModel<String> alienListModel;
private JList<String> alienList;
//private javax.swing.JScrollPane jScrollPane1;


    /**
     * Creates new form AlienInformationPlats
     */
    public AlienInformationPlats(InfDB idb) {
        initComponents();
        this.idb = idb;
        alienListModel = new DefaultListModel<>();
        alienList = new JList<>(alienListModel);
//       jScrollPane1= new javax.swing.JScrollPane();
//       jScrollPane1.setViewportView(alienList);
    } 

    AlienInformationPlats() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAlienPlats = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jAngePlats = new javax.swing.JTextField();
        jSök = new javax.swing.JButton();
        jFelMeddelande = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jResultat = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAlienPlats.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sök alien plats", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 24))); // NOI18N

        jLabel1.setText("Plats nummer");

        jAngePlats.setText("Ange plats nummer");

        jSök.setText("Sök");
        jSök.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSökActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jResultat);

        javax.swing.GroupLayout jAlienPlatsLayout = new javax.swing.GroupLayout(jAlienPlats);
        jAlienPlats.setLayout(jAlienPlatsLayout);
        jAlienPlatsLayout.setHorizontalGroup(
            jAlienPlatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlienPlatsLayout.createSequentialGroup()
                .addGroup(jAlienPlatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jAlienPlatsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jAngePlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jAlienPlatsLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jSök))
                    .addGroup(jAlienPlatsLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jFelMeddelande)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jAlienPlatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
        );
        jAlienPlatsLayout.setVerticalGroup(
            jAlienPlatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAlienPlatsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jAlienPlatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jAngePlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jFelMeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSök)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAlienPlats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jAlienPlats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSökActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSökActionPerformed
        try{
        String PlatsNummer = jAngePlats.getText();
        String query = "Select * from Alien where Plats = " + PlatsNummer;
        
        
       
        ArrayList<HashMap<String, String>> allaAlien = idb.fetchRows(query);
        
// Används för att rensa listan.  
        alienListModel.clear();
       
        
        for(HashMap<String, String> Alien : allaAlien) {
            
//Skapa en string builder med namnet alieninfo. 
//Används för att bygga och manipulera strängar.

            StringBuilder alieninfo = new StringBuilder();
            for(String info : Alien.values()) {
                
// Lägga till info i listan alieninfo.               
                alieninfo.append(info).append("\t");
            }
            
// Lägger till information från alieninfo i jResultat.          
            alienListModel.addElement(alieninfo.toString());
        }
        
// Kopplar alienListModel med jResultat.       
        jResultat.setModel(alienListModel);
        
    } catch (InfException fel) {
          jFelMeddelande.setText("Inloggningen lyckades inte, försök igen senare!");}
        
    }//GEN-LAST:event_jSökActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AlienInformationPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AlienInformationPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AlienInformationPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AlienInformationPlats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//            new AlienInformationPlats(idb).setVisible(true);
//            }
//        
//    
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jAlienPlats;
    private javax.swing.JTextField jAngePlats;
    private javax.swing.JLabel jFelMeddelande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jResultat;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSök;
    // End of variables declaration//GEN-END:variables

}