package realiseringprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB; 
import oru.inf.InfException;

/**
 *
 * @author leyla
 */

public class Inloggning extends javax.swing.JFrame {

    private InfDB idb;
    
    /**
     * Creates new form Inloggning
     */
    public Inloggning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSvartBakgrund = new javax.swing.JPanel();
        mibBild = new javax.swing.JLabel();
        pnlHogerGraSida = new javax.swing.JPanel();
        pwdSkrivaLosenord = new javax.swing.JPasswordField();
        txtSkrivaEpost = new javax.swing.JTextField();
        lblSysteminloggning = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblGlomtLosenord = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        btnLoggaIn = new javax.swing.JButton();
        lblEpost = new javax.swing.JLabel();
        lblFelmeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlSvartBakgrund.setBackground(new java.awt.Color(0, 0, 0));

        mibBild.setIcon(new javax.swing.ImageIcon("C:\\Users\\leyla\\OneDrive\\Bilder\\Skärmbild 2023-12-14 172404.png")); // NOI18N

        javax.swing.GroupLayout pnlSvartBakgrundLayout = new javax.swing.GroupLayout(pnlSvartBakgrund);
        pnlSvartBakgrund.setLayout(pnlSvartBakgrundLayout);
        pnlSvartBakgrundLayout.setHorizontalGroup(
            pnlSvartBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSvartBakgrundLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(mibBild, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlSvartBakgrundLayout.setVerticalGroup(
            pnlSvartBakgrundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSvartBakgrundLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(mibBild, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHogerGraSida.setBackground(new java.awt.Color(102, 102, 102));

        pwdSkrivaLosenord.setBackground(new java.awt.Color(153, 153, 153));
        pwdSkrivaLosenord.setForeground(new java.awt.Color(0, 0, 0));

        txtSkrivaEpost.setBackground(new java.awt.Color(153, 153, 153));
        txtSkrivaEpost.setForeground(new java.awt.Color(0, 0, 0));

        lblSysteminloggning.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSysteminloggning.setForeground(new java.awt.Color(255, 255, 255));
        lblSysteminloggning.setText("Systeminloggning");

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLosenord.setForeground(new java.awt.Color(255, 255, 255));
        lblLosenord.setText("Lösenord");

        lblGlomtLosenord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGlomtLosenord.setForeground(new java.awt.Color(255, 255, 255));
        lblGlomtLosenord.setText("Glömt lösenord?");

        btnAndraLosenord.setText("Ändra lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        btnLoggaIn.setBackground(new java.awt.Color(0, 153, 51));
        btnLoggaIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLoggaIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lblEpost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEpost.setForeground(new java.awt.Color(255, 255, 255));
        lblEpost.setText("E-post");

        lblFelmeddelande.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFelmeddelande.setForeground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout pnlHogerGraSidaLayout = new javax.swing.GroupLayout(pnlHogerGraSida);
        pnlHogerGraSida.setLayout(pnlHogerGraSidaLayout);
        pnlHogerGraSidaLayout.setHorizontalGroup(
            pnlHogerGraSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHogerGraSidaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(pnlHogerGraSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHogerGraSidaLayout.createSequentialGroup()
                        .addGroup(pnlHogerGraSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSysteminloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSkrivaEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdSkrivaLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlHogerGraSidaLayout.createSequentialGroup()
                        .addGroup(pnlHogerGraSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGlomtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 87, Short.MAX_VALUE))))
        );
        pnlHogerGraSidaLayout.setVerticalGroup(
            pnlHogerGraSidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHogerGraSidaLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(lblSysteminloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtSkrivaEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdSkrivaLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblGlomtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSvartBakgrund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHogerGraSida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSvartBakgrund, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlHogerGraSida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        // Knappen skickar användaren till sidan för att ändra lösenord
        AndraLosenord andra = new AndraLosenord(idb);
        andra.show();
        dispose();
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        // Logga in-knappen skickar användaren vidare ifall e-post och lösenord stämmer överens
        // Funkar just nu endast för tabellen agent (ej specifikt ifall admin eller ej)
        //Bör skapas en ny separat metod för att kunna göra koden kortare för alla ranker!
        String epostRuta = txtSkrivaEpost.getText();
        String losenordRuta = new String(pwdSkrivaLosenord.getPassword());

        String fraga = "SELECT Epost, Losenord from agent";

        try {
            ArrayList<HashMap<String, String>> allaAgenter = idb.fetchRows(fraga);
            
            for (HashMap<String, String> enAgent : allaAgenter) {
                String agentEpost = enAgent.get("Epost");
                String agentLosenord = enAgent.get("Losenord");

                if (epostRuta.equals(agentEpost) && losenordRuta.equals(agentLosenord)) {
                    AdminSida admin = new AdminSida(idb);
                    admin.show();
                    dispose();
                    return;
                }
            }

            lblFelmeddelande.setText("E-post och lösenord stämmer ej överens.");

        } catch (InfException fel) {
            lblFelmeddelande.setText("Ett fel uppstod vid inloggning!");
        }
    }//GEN-LAST:event_btnLoggaInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblGlomtLosenord;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblSysteminloggning;
    private javax.swing.JLabel mibBild;
    private javax.swing.JPanel pnlHogerGraSida;
    private javax.swing.JPanel pnlSvartBakgrund;
    private javax.swing.JPasswordField pwdSkrivaLosenord;
    private javax.swing.JTextField txtSkrivaEpost;
    // End of variables declaration//GEN-END:variables
}
