
package realiseringprojekt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author charolinnoaaman
 */
public class LoggaIn extends javax.swing.JFrame {

    private InfDB idb;
    /**
     * Creates new form LoggaIn
     */
    public LoggaIn() {
        this.idb = idb;
        initComponents();
        
        
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bLoggain = new javax.swing.JButton();
        jEpost = new javax.swing.JTextField();
        jLösenord = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        ändra = new javax.swing.JButton();
        jFelMeddelande = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Epost");

        jLabel2.setText("Lösenord");

        bLoggain.setText("Logga in");
        bLoggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoggainActionPerformed(evt);
            }
        });

        jEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEpostActionPerformed(evt);
            }
        });

        jLösenord.setText("jPasswordField1");
        jLösenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLösenordActionPerformed(evt);
            }
        });

        ändra.setText("Ändra lösenord");
        ändra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ändraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFelMeddelande)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ändra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bLoggain)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLösenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jFelMeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoggain)
                    .addComponent(ändra))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLoggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoggainActionPerformed
        
        String Epost = jEpost.getText();
        String Lösenord = new String(jLösenord.getPassword());
        
        
       String query = "SELECT Epost, Lösenord FROM agent";
       
       
       try {
           ArrayList<HashMap<String, String>> allaAgenter = idb.fetchRows(query);
           
           for(HashMap<String, String> enAgent : allaAgenter) {
            String epost = enAgent.get("Epost");
            String lösenord = enAgent.get("Lösenord");
            
          
           if (Epost.equals(epost) && Lösenord.equals(lösenord)) {
               JOptionPane.showMessageDialog(null, "Inloggningen lyckades!");
               AgentFönster fönster = new AgentFönster(idb);
               fönster.setVisible(true);
               return;
              
               
           }
           else if(jEpost.getText().equals("")) {
          JOptionPane.showMessageDialog(null, "Fyll i din epost");
            
        }
           else if (jLösenord.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Fyll i ditt lösenord");
            
          
        } 
        
            
            
           }
       } catch (InfException fel) {
            jFelMeddelande.setText("Inloggningen lyckades inte, försök igen senare!");
        }
       
     
      
       
        
    }//GEN-LAST:event_bLoggainActionPerformed

    private void jEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEpostActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jEpostActionPerformed

    private void jLösenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLösenordActionPerformed
        // ODO add your handling code here:
    }//GEN-LAST:event_jLösenordActionPerformed

    private void ändraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ändraActionPerformed
      
    }//GEN-LAST:event_ändraActionPerformed

        public static void main(String args[]) {
        


java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
       new LoggaIn().setVisible(true);
    }
        });
        }
   
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLoggain;
    private javax.swing.JTextField jEpost;
    private javax.swing.JLabel jFelMeddelande;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jLösenord;
    private javax.swing.JButton ändra;
    // End of variables declaration//GEN-END:variables
}
